In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import time

In [2]:
y2015 = pd.read_csv('LoanStats3d.csv',skipinitialspace=True, header=1)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
y2015 = y2015[:-2]
y2015.dropna(axis=1, thresh=20000,inplace=True)

In [4]:
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

y2015.drop(['emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state'], 1, inplace=True)

In [5]:
pd.get_dummies(y2015)

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,...,last_credit_pull_d_Sep-2016,last_credit_pull_d_Sep-2017,last_credit_pull_d_Sep-2018,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,disbursement_method_Cash,debt_settlement_flag_N,debt_settlement_flag_Y
0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
1,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,3.0,12.0,...,0,0,0,1,0,1,0,1,1,0
2,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,0.0,NaN,...,0,0,0,0,1,1,0,1,1,0
3,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,1.0,30.0,...,0,0,0,1,0,1,0,1,1,0
4,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,4.0,6.0,...,0,0,0,1,0,1,0,1,1,0
5,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
6,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
7,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,0.0,49.0,...,0,0,0,1,0,1,0,1,1,0
8,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,0.0,NaN,...,0,0,1,1,0,1,0,1,1,0
9,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
10,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,0.0,54.0,...,0,0,0,1,0,1,0,1,1,0
11,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
12,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,0.0,75.0,...,0,0,0,1,0,1,0,1,1,0
13,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,0.0,3.0,...,0,0,0,1,0,1,0,1,1,0
14,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,0.0,42.0,...,0,0,0,1,0,1,0,1,1,0
15,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,0.0,29.0,...,0,0,0,1,0,1,0,1,1,0
16,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,4.0,NaN,...,0,0,0,1,0,1,0,1,1,0
17,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
18,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
19,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,0.0,33.0,...,0,1,0,1,0,1,0,1,1,0
20,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
21,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
22,16000.0,16000.0,16000.0,12.88,363.07,90000.0,6.39,0.0,0.0,26.0,...,0,0,0,1,0,1,0,1,1,0
23,4200.0,4200.0,4200.0,13.99,143.53,32000.0,31.02,0.0,2.0,50.0,...,0,0,0,1,0,1,0,1,1,0
24,12000.0,12000.0,12000.0,9.17,382.55,39400.0,26.32,0.0,1.0,68.0,...,0,0,0,1,0,1,0,1,1,0
25,4000.0,4000.0,4000.0,9.17,127.52,44500.0,15.83,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
26,14000.0,14000.0,14000.0,9.80,450.43,100000.0,15.97,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
27,10500.0,10500.0,10500.0,15.77,367.96,70100.0,8.51,0.0,0.0,35.0,...,0,0,0,1,0,1,0,1,1,0
28,10000.0,10000.0,10000.0,11.48,329.67,33000.0,21.75,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
29,15000.0,15000.0,15000.0,9.80,482.61,92000.0,13.89,0.0,1.0,NaN,...,0,1,0,1,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,0.0,38.0,...,0,0,0,1,0,1,0,1,1,0
421066,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,1.0,69.0,...,0,0,0,1,0,1,0,1,1,0
421067,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421068,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,0.0,15.0,...,0,0,0,1,0,1,0,1,1,0
421069,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421070,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421071,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421072,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,0.0,30.0,...,0,0,0,1,0,1,0,1,1,0
421073,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421074,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421075,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421076,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,0.0,17.0,...,0,0,0,1,0,1,0,1,1,0
421077,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,1.0,24.0,...,0,0,0,1,0,1,0,1,1,0
421078,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421079,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,0.0,8.0,...,0,0,0,1,0,1,0,1,1,0
421080,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,0.0,16.0,...,0,0,0,1,0,1,0,1,1,0
421081,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,3.0,10.0,...,0,0,0,1,0,1,0,1,1,0
421082,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421083,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421084,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,0.0,29.0,...,0,0,0,1,0,1,0,1,1,0
421085,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421086,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,1.0,65.0,...,0,0,0,1,0,1,0,1,1,0
421087,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,0.0,69.0,...,0,0,0,1,0,1,0,1,1,0
421088,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421089,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,0.0,9.0,...,0,0,0,1,0,1,0,1,1,0
421090,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421091,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,1.0,26.0,...,0,0,0,1,0,1,0,1,1,0
421092,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421093,12000.0,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,2.0,22.0,...,0,0,0,1,0,1,0,1,1,0
421094,20000.0,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0

In [6]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

start_time = time.time()
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.99045448, 0.99069193, 0.99000285, 0.99237693, 0.992258  ,
       0.9915693 , 0.99237675, 0.99301795, 0.99225782, 0.99323153])

In [7]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 183.68471813201904 seconds ---

In [9]:
from sklearn import tree
start_time = time.time()
decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=1,
    max_depth=4  
)

cross_val_score(decision_tree, X, Y, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))

--- 29.804687976837158 seconds ---

## random forest with no PCA took 184 seconds while decision tree took 30 seconds.