In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
y2015 = pd.read_csv('LoanStats3d.csv',skipinitialspace=True, header=1)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
y2015 = y2015[:-2]
y2015.dropna(axis=1, thresh=20000,inplace=True)

In [4]:
y2015.tail()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
421090,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,B5,Office Assistant,8 years,...,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0,N,Cash,N
421091,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,B5,Director of Maintenance,10+ years,...,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0,N,Cash,N
421092,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,D2,Radiologist Technologist,5 years,...,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0,N,Cash,N
421093,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,E3,Painter,1 year,...,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0,N,Cash,N
421094,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,B5,Manager Hotel Operations Oasis,10+ years,...,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0,N,Cash,N

In [5]:
y2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421095 entries, 0 to 421094
Columns: 106 entries, loan_amnt to debt_settlement_flag
dtypes: float64(81), object(25)
memory usage: 340.5+ MB

In [6]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
int_rate
111
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
2
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
50
next_pymnt_d
6
last_credit_pull_d
51
application_type
2
hardship_flag
2
disbursement_method
1
debt_settlement_flag
2

In [7]:
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

y2015.drop(['emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state'], 1, inplace=True)

In [8]:
pd.get_dummies(y2015)

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,...,last_credit_pull_d_Sep-2016,last_credit_pull_d_Sep-2017,last_credit_pull_d_Sep-2018,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,disbursement_method_Cash,debt_settlement_flag_N,debt_settlement_flag_Y
0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
1,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,3.0,12.0,...,0,0,0,1,0,1,0,1,1,0
2,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,0.0,NaN,...,0,0,0,0,1,1,0,1,1,0
3,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,1.0,30.0,...,0,0,0,1,0,1,0,1,1,0
4,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,4.0,6.0,...,0,0,0,1,0,1,0,1,1,0
5,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
6,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
7,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,0.0,49.0,...,0,0,0,1,0,1,0,1,1,0
8,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,0.0,NaN,...,0,0,1,1,0,1,0,1,1,0
9,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
10,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,0.0,54.0,...,0,0,0,1,0,1,0,1,1,0
11,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
12,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,0.0,75.0,...,0,0,0,1,0,1,0,1,1,0
13,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,0.0,3.0,...,0,0,0,1,0,1,0,1,1,0
14,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,0.0,42.0,...,0,0,0,1,0,1,0,1,1,0
15,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,0.0,29.0,...,0,0,0,1,0,1,0,1,1,0
16,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,4.0,NaN,...,0,0,0,1,0,1,0,1,1,0
17,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
18,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
19,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,0.0,33.0,...,0,1,0,1,0,1,0,1,1,0
20,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
21,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
22,16000.0,16000.0,16000.0,12.88,363.07,90000.0,6.39,0.0,0.0,26.0,...,0,0,0,1,0,1,0,1,1,0
23,4200.0,4200.0,4200.0,13.99,143.53,32000.0,31.02,0.0,2.0,50.0,...,0,0,0,1,0,1,0,1,1,0
24,12000.0,12000.0,12000.0,9.17,382.55,39400.0,26.32,0.0,1.0,68.0,...,0,0,0,1,0,1,0,1,1,0
25,4000.0,4000.0,4000.0,9.17,127.52,44500.0,15.83,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
26,14000.0,14000.0,14000.0,9.80,450.43,100000.0,15.97,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
27,10500.0,10500.0,10500.0,15.77,367.96,70100.0,8.51,0.0,0.0,35.0,...,0,0,0,1,0,1,0,1,1,0
28,10000.0,10000.0,10000.0,11.48,329.67,33000.0,21.75,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
29,15000.0,15000.0,15000.0,9.80,482.61,92000.0,13.89,0.0,1.0,NaN,...,0,1,0,1,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,0.0,38.0,...,0,0,0,1,0,1,0,1,1,0
421066,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,1.0,69.0,...,0,0,0,1,0,1,0,1,1,0
421067,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421068,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,0.0,15.0,...,0,0,0,1,0,1,0,1,1,0
421069,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421070,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421071,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421072,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,0.0,30.0,...,0,0,0,1,0,1,0,1,1,0
421073,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421074,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421075,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421076,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,0.0,17.0,...,0,0,0,1,0,1,0,1,1,0
421077,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,1.0,24.0,...,0,0,0,1,0,1,0,1,1,0
421078,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421079,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,0.0,8.0,...,0,0,0,1,0,1,0,1,1,0
421080,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,0.0,16.0,...,0,0,0,1,0,1,0,1,1,0
421081,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,3.0,10.0,...,0,0,0,1,0,1,0,1,1,0
421082,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421083,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421084,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,0.0,29.0,...,0,0,0,1,0,1,0,1,1,0
421085,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421086,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,1.0,65.0,...,0,0,0,1,0,1,0,1,1,0
421087,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,0.0,69.0,...,0,0,0,1,0,1,0,1,1,0
421088,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421089,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,0.0,9.0,...,0,0,0,1,0,1,0,1,1,0
421090,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421091,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,1.0,26.0,...,0,0,0,1,0,1,0,1,1,0
421092,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,0.0,NaN,...,0,0,0,1,0,1,0,1,1,0
421093,12000.0,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,2.0,22.0,...,0,0,0,1,0,1,0,1,1,0
421094,20000.0,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,1.0,NaN,...,0,0,0,1,0,1,0,1,1,0

In [9]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98993209, 0.98926723, 0.99050152, 0.99168824, 0.99183053,
       0.99128432, 0.99104683, 0.9930892 , 0.99301779, 0.99259031])

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)
principalDf.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,263636.671395,-10322.591249,51285.884562,28905.804763,17712.380870,-34738.204272,-16550.666965,-5066.540421,1809.417565,17422.153455,...,-0.802498,0.303507,-0.197150,0.835258,0.214588,-0.561621,-0.545836,0.672934,0.365100,-0.302020
1,330915.170803,-16161.293833,-15974.124774,-22332.295185,36524.432733,21241.397545,10950.395440,-9836.413271,-259.886666,2301.382269,...,1.105552,0.852156,-0.504651,-1.042981,0.853926,-0.876549,-0.051822,-0.341286,-0.266565,0.569474
2,55892.560597,-36618.413858,48309.198473,-24038.123409,-3414.921770,-17079.484709,13630.897056,3145.479804,10534.313334,2381.427102,...,0.543002,0.083707,-0.379072,-0.112015,0.155520,0.588009,-0.432801,-0.593755,-0.350122,-0.230913
3,-7629.499733,-39068.147755,49308.584863,-28607.543598,4512.080931,22900.119892,2474.680826,1588.568642,3171.273143,-1617.221663,...,-0.607802,0.078878,-0.513208,-0.175742,0.780716,0.495183,-0.790462,0.560436,-0.458171,-0.869700
4,148488.673572,-29968.962705,29192.600840,89613.658027,37403.238644,-18038.901538,-27512.189695,11818.524320,-686.597370,8784.428730,...,1.052870,2.686966,-0.810383,-1.131298,0.734263,0.437996,-0.582674,0.610101,-0.462856,-1.047329

In [12]:
X_pca_10 = principalDf
Y = y2015['loan_status']
X_pca_10 = pd.get_dummies(X_pca_10)
X_pca_10 = X_pca_10.dropna(axis=1)

cross_val_score(rfc, X_pca_10, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98648905, 0.98786627, 0.98736702, 0.98715239, 0.98760331,
       0.98833951, 0.98800703, 0.98850575, 0.98750802, 0.98586933])

In [13]:
pca = PCA(n_components=40)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [14]:
X_pca_40 = principalDf
Y = y2015['loan_status']
X_pca_40 = pd.get_dummies(X_pca_40)
X_pca_40 = X_pca_40.dropna(axis=1)

cross_val_score(rfc, X_pca_40, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98736762, 0.98817495, 0.98736702, 0.9875561 , 0.98755581,
       0.98829201, 0.98784079, 0.98869573, 0.98760301, 0.98596433])

In [15]:
pca = PCA(n_components=30)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [16]:
X_pca_30 = principalDf
Y = y2015['loan_status']
X_pca_30 = pd.get_dummies(X_pca_30)
X_pca_30 = X_pca_30.dropna(axis=1)

cross_val_score(rfc, X_pca_30, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98691646, 0.98876858, 0.98836436, 0.98731863, 0.98810202,
       0.98814952, 0.98798328, 0.98855324, 0.98795925, 0.98648681])

In [17]:
pca = PCA(n_components=20)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [18]:
X_pca_20 = principalDf
Y = y2015['loan_status']
X_pca_20 = pd.get_dummies(X_pca_20)
X_pca_20 = X_pca_20.dropna(axis=1)

cross_val_score(rfc, X_pca_20, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98644156, 0.98838866, 0.98767572, 0.98798357, 0.98793578,
       0.98824451, 0.98824451, 0.98855324, 0.98748427, 0.98703303])

In [19]:
pca = PCA(n_components=10)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [20]:
X_pca_10 = principalDf
Y = y2015['loan_status']
X_pca_10 = pd.get_dummies(X_pca_10)
X_pca_10 = X_pca_10.dropna(axis=1)

cross_val_score(rfc, X_pca_10, Y, cv=10)

c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\shuaix\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.72353612, 0.72341739, 0.72613507, 0.72670925, 0.72575283,
       0.72513537, 0.72660777, 0.72050442, 0.721139  , 0.72251645])

## The average accuracy dropped from ~99% to 72% somewhere between 20 to 30 components in PCA.